"""Per-trophy gadget requirements.

Derived from a full read of the GamesRadar Riddler trophy guide, which is
usable as logic data because its trophy numbering was confirmed to be the
game's own PickupIndex (Museum #3, "the catwalk above the T-Rex", logged
in-game as RiddlerLoc_Museum index 3).

Requirements were extracted by matching gadget mentions in each entry's
text. Gadgets deliberately NOT gated, because the player always has them:
Batclaw, Grapnel/grapple, dive bomb and glide moves, and the Cryptographic
Sequencer (a story unlock, and not part of the wheel gadget system at all).

"Magnetic Blast" is the internal name for the Remote Electrical Charge.

LOCATION_REQUIREMENTS      - every listed gadget is required (AND).
LOCATION_ANY_REQUIREMENTS  - any ONE of the listed gadgets suffices (OR).
                             Hand-corrected from entries offering a choice,
                             which the text parser would otherwise treat as
                             requiring both.
UNKNOWN_LOCATIONS          - no usable guide text (the guide merges some
                             entries under a combined heading, e.g.
                             "22-23-24"). Excluded from holding progression
                             rather than guessed at.
"""

LOCATION_REQUIREMENTS = {
    "RiddlerLoc_Museum_1": [],
    "RiddlerLoc_Museum_2": ["Explosive Gel"],
    "RiddlerLoc_Museum_3": [],
    "RiddlerLoc_Museum_4": ["Disruptor"],
    "RiddlerLoc_Museum_5": [],
    "RiddlerLoc_Museum_6": ["Magnetic Blast"],
    "RiddlerLoc_Museum_7": ["Line Launcher"],
    "RiddlerLoc_Museum_8": ["Remote-Control Batarang"],
    "RiddlerLoc_Museum_9": [],
    "RiddlerLoc_Museum_10": [],
    "RiddlerLoc_Museum_11": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_Museum_12": ["Freeze Blast"],
    "RiddlerLoc_Museum_13": ["Line Launcher"],
    "RiddlerLoc_Museum_14": ["Line Launcher", "Freeze Blast"],
    "RiddlerLoc_Museum_15": [],
    "RiddlerLoc_Museum_16": ["Freeze Blast"],
    "RiddlerLoc_Museum_17": ["Disruptor"],
    "RiddlerLoc_Museum_18": ["Magnetic Blast"],
    "RiddlerLoc_Museum_19": [],
    "RiddlerLoc_Museum_20": ["Freeze Blast"],
    "RiddlerLoc_Museum_21": [],
    "RiddlerLoc_Museum_22": [],
    "RiddlerLoc_Museum_23": [],
    "RiddlerLoc_OWA_1": [],
    "RiddlerLoc_OWA_2": ["Disruptor"],
    "RiddlerLoc_OWA_3": ["Disruptor"],
    "RiddlerLoc_OWA_4": [],
    "RiddlerLoc_OWA_5": [],
    "RiddlerLoc_OWA_6": ["Explosive Gel"],
    "RiddlerLoc_OWA_7": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_OWA_8": [],
    "RiddlerLoc_OWA_9": [],
    "RiddlerLoc_OWA_10": [],
    "RiddlerLoc_OWA_11": ["Magnetic Blast"],
    "RiddlerLoc_OWA_12": ["Magnetic Blast"],
    "RiddlerLoc_OWA_13": [],
    "RiddlerLoc_OWA_14": ["Freeze Blast"],
    "RiddlerLoc_OWA_15": [],
    "RiddlerLoc_OWA_16": [],
    "RiddlerLoc_OWA_17": ["Explosive Gel"],
    "RiddlerLoc_OWA_18": ["Remote-Control Batarang"],
    "RiddlerLoc_OWA_19": ["Freeze Blast"],
    "RiddlerLoc_OWA_20": [],
    "RiddlerLoc_OWA_21": ["Explosive Gel"],
    "RiddlerLoc_OWA_22": [],
    "RiddlerLoc_OWA_23": ["Explosive Gel"],
    "RiddlerLoc_OWA_24": [],
    "RiddlerLoc_OWA_25": ["Disruptor", "Explosive Gel"],
    "RiddlerLoc_OWA_26": [],
    "RiddlerLoc_OWA_27": ["Freeze Blast"],
    "RiddlerLoc_OWA_28": [],
    "RiddlerLoc_OWA_29": ["Line Launcher"],
    "RiddlerLoc_OWA_30": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_OWA_31": [],
    "RiddlerLoc_OWA_32": [],
    "RiddlerLoc_OWA_33": ["Line Launcher"],
    "RiddlerLoc_OWA_34": [],
    "RiddlerLoc_OWA_35": ["Remote-Control Batarang"],
    "RiddlerLoc_OWA_36": [],
    "RiddlerLoc_OWB_1": ["Disruptor", "Freeze Blast"],
    "RiddlerLoc_OWB_2": ["Explosive Gel"],
    "RiddlerLoc_OWB_3": ["Line Launcher"],
    "RiddlerLoc_OWB_4": [],
    "RiddlerLoc_OWB_6": [],
    "RiddlerLoc_OWB_7": ["Explosive Gel"],
    "RiddlerLoc_OWB_8": ["Disruptor"],
    "RiddlerLoc_OWB_9": [],
    "RiddlerLoc_OWB_10": [],
    "RiddlerLoc_OWB_11": ["Magnetic Blast"],
    "RiddlerLoc_OWB_12": [],
    "RiddlerLoc_OWB_13": [],
    "RiddlerLoc_OWB_14": ["Magnetic Blast"],
    "RiddlerLoc_OWB_15": ["Remote-Control Batarang"],
    "RiddlerLoc_OWB_16": [],
    "RiddlerLoc_OWB_17": ["Explosive Gel"],
    "RiddlerLoc_OWB_18": [],
    "RiddlerLoc_OWB_19": [],
    "RiddlerLoc_OWB_20": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_OWB_21": [],
    "RiddlerLoc_OWB_22": [],
    "RiddlerLoc_OWB_23": ["Freeze Blast"],
    "RiddlerLoc_OWB_24": ["Remote-Control Batarang"],
    "RiddlerLoc_OWB_25": [],
    "RiddlerLoc_OWB_26": [],
    "RiddlerLoc_OWB_27": ["Explosive Gel", "Freeze Blast"],
    "RiddlerLoc_OWB_28": ["Explosive Gel"],
    "RiddlerLoc_OWB_29": ["Freeze Blast"],
    "RiddlerLoc_OWB_30": ["Magnetic Blast"],
    "RiddlerLoc_OWB_31": [],
    "RiddlerLoc_OWB_32": [],
    "RiddlerLoc_OWB_33": ["Explosive Gel"],
    "RiddlerLoc_OWB_34": [],
    "RiddlerLoc_OWB_35": ["Remote-Control Batarang"],
    "RiddlerLoc_OWB_36": ["Line Launcher"],
    "RiddlerLoc_OWB_37": [],
    "RiddlerLoc_OWC_1": ["Magnetic Blast"],
    "RiddlerLoc_OWC_2": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_OWC_3": [],
    "RiddlerLoc_OWC_4": [],
    "RiddlerLoc_OWC_5": [],
    "RiddlerLoc_OWC_6": ["Line Launcher"],
    "RiddlerLoc_OWC_7": [],
    "RiddlerLoc_OWC_8": [],
    "RiddlerLoc_OWC_9": ["Magnetic Blast"],
    "RiddlerLoc_OWC_10": [],
    "RiddlerLoc_OWC_11": ["Line Launcher"],
    "RiddlerLoc_OWC_12": [],
    "RiddlerLoc_OWC_13": [],
    "RiddlerLoc_OWC_14": [],
    "RiddlerLoc_OWC_15": ["Remote-Control Batarang"],
    "RiddlerLoc_OWC_16": ["Explosive Gel", "Magnetic Blast"],
    "RiddlerLoc_OWC_17": [],
    "RiddlerLoc_OWC_18": ["Explosive Gel"],
    "RiddlerLoc_OWC_19": [],
    "RiddlerLoc_OWC_20": [],
    "RiddlerLoc_OWC_21": ["Freeze Blast"],
    "RiddlerLoc_OWC_22": [],
    "RiddlerLoc_OWC_23": ["Freeze Blast"],
    "RiddlerLoc_OWC_24": ["Remote-Control Batarang"],
    "RiddlerLoc_OWC_25": [],
    "RiddlerLoc_OWC_26": [],
    "RiddlerLoc_OWC_27": [],
    "RiddlerLoc_OWC_28": ["Disruptor"],
    "RiddlerLoc_OWC_29": ["Magnetic Blast"],
    "RiddlerLoc_OWC_30": [],
    "RiddlerLoc_OWC_31": ["Remote-Control Batarang"],
    "RiddlerLoc_OWC_32": ["Disruptor", "Freeze Blast"],
    "RiddlerLoc_OWC_33": [],
    "RiddlerLoc_OWC_34": [],
    "RiddlerLoc_OWC_35": ["Line Launcher"],
    "RiddlerLoc_OWC_36": ["Explosive Gel"],
    "RiddlerLoc_OWC_37": [],
    "RiddlerLoc_OWD_1": [],
    "RiddlerLoc_OWD_2": [],
    "RiddlerLoc_OWD_3": [],
    "RiddlerLoc_OWD_4": ["Explosive Gel"],
    "RiddlerLoc_OWD_5": [],
    "RiddlerLoc_OWD_6": [],
    "RiddlerLoc_OWD_7": ["Remote-Control Batarang"],
    "RiddlerLoc_OWD_8": ["Line Launcher"],
    "RiddlerLoc_OWD_11": [],
    "RiddlerLoc_OWD_12": [],
    "RiddlerLoc_OWD_13": [],
    "RiddlerLoc_OWD_14": ["Magnetic Blast"],
    "RiddlerLoc_OWD_15": [],
    "RiddlerLoc_OWD_16": ["Magnetic Blast"],
    "RiddlerLoc_OWD_17": ["Freeze Blast"],
    "RiddlerLoc_OWD_18": [],
    "RiddlerLoc_OWD_19": [],
    "RiddlerLoc_OWD_20": ["Line Launcher"],
    "RiddlerLoc_OWD_21": [],
    "RiddlerLoc_OWD_22": ["Explosive Gel", "Freeze Blast"],
    "RiddlerLoc_OWD_25": ["Freeze Blast"],
    "RiddlerLoc_OWD_26": ["Remote-Control Batarang"],
    "RiddlerLoc_OWE_1": [],
    "RiddlerLoc_OWE_2": [],
    "RiddlerLoc_OWE_3": [],
    "RiddlerLoc_OWE_4": [],
    "RiddlerLoc_OWE_5": ["Magnetic Blast"],
    "RiddlerLoc_OWE_6": ["Explosive Gel"],
    "RiddlerLoc_OWE_7": ["Line Launcher"],
    "RiddlerLoc_OWE_8": [],
    "RiddlerLoc_OWE_9": [],
    "RiddlerLoc_OWE_10": [],
    "RiddlerLoc_OWE_11": [],
    "RiddlerLoc_OWE_12": [],
    "RiddlerLoc_OWE_13": ["Line Launcher"],
    "RiddlerLoc_OWE_14": [],
    "RiddlerLoc_OWE_15": [],
    "RiddlerLoc_OWE_16": [],
    "RiddlerLoc_OWE_17": [],
    "RiddlerLoc_OWE_18": ["Magnetic Blast"],
    "RiddlerLoc_OWE_19": [],
    "RiddlerLoc_OWE_20": ["Disruptor", "Explosive Gel"],
    "RiddlerLoc_OWE_21": [],
    "RiddlerLoc_OWE_22": ["Explosive Gel"],
    "RiddlerLoc_OWE_23": ["Magnetic Blast"],
    "RiddlerLoc_OWE_24": [],
    "RiddlerLoc_OWE_25": ["Remote-Control Batarang"],
    "RiddlerLoc_OWE_26": [],
    "RiddlerLoc_OWE_27": [],
    "RiddlerLoc_OWE_28": ["Explosive Gel"],
    "RiddlerLoc_OWE_29": ["Explosive Gel"],
    "RiddlerLoc_OWE_30": [],
    "RiddlerLoc_OWE_31": ["Freeze Blast"],
    "RiddlerLoc_OWE_32": [],
    "RiddlerLoc_OWE_33": [],
    "RiddlerLoc_OWE_34": ["Line Launcher"],
    "RiddlerLoc_OWE_35": ["Freeze Blast"],
    "RiddlerLoc_OWE_36": [],
    "RiddlerLoc_OWE_37": ["Explosive Gel"],
    "RiddlerLoc_OWE_38": [],
    "RiddlerLoc_OWE_39": [],
    "RiddlerLoc_Steel_1": ["Explosive Gel"],
    "RiddlerLoc_Steel_3": ["Line Launcher"],
    "RiddlerLoc_Steel_4": ["Remote-Control Batarang"],
    "RiddlerLoc_Steel_5": ["Freeze Blast"],
    "RiddlerLoc_Steel_6": [],
    "RiddlerLoc_Steel_7": [],
    "RiddlerLoc_Steel_8": ["Magnetic Blast"],
    "RiddlerLoc_Steel_9": [],
    "RiddlerLoc_Steel_10": [],
    "RiddlerLoc_Steel_11": [],
    "RiddlerLoc_Steel_12": ["Explosive Gel"],
    "RiddlerLoc_Steel_13": ["Freeze Blast", "Magnetic Blast"],
    "RiddlerLoc_Steel_14": [],
    "RiddlerLoc_Steel_15": [],
    "RiddlerLoc_Steel_16": ["Freeze Blast"],
    "RiddlerLoc_Steel_17": ["Magnetic Blast"],
    "RiddlerLoc_Steel_18": [],
    "RiddlerLoc_Steel_19": ["Line Launcher"],
    "RiddlerLoc_Steel_20": [],
    "RiddlerLoc_Steel_21": [],
    "RiddlerLoc_Steel_22": [],
    "RiddlerLoc_Steel_23": ["Explosive Gel"],
    "RiddlerLoc_Steel_24": [],
    "RiddlerLoc_Underworld_1": ["Freeze Blast"],
    "RiddlerLoc_Underworld_2": [],
    "RiddlerLoc_Underworld_3": ["Freeze Blast"],
    "RiddlerLoc_Underworld_4": ["Explosive Gel", "Line Launcher"],
    "RiddlerLoc_Underworld_5": [],
    "RiddlerLoc_Underworld_6": ["Freeze Blast"],
    "RiddlerLoc_Underworld_7": [],
    "RiddlerLoc_Underworld_8": [],
    "RiddlerLoc_Underworld_9": [],
    "RiddlerLoc_Underworld_10": [],
    "RiddlerLoc_Underworld_11": ["Explosive Gel"],
    "RiddlerLoc_Underworld_12": [],
    "RiddlerLoc_Underworld_13": [],
    "RiddlerLoc_Underworld_14": [],
    "RiddlerLoc_Underworld_15": ["Freeze Blast"],
    "RiddlerLoc_Underworld_16": ["Line Launcher", "Freeze Blast"],
    "RiddlerLoc_Underworld_17": ["Line Launcher"],
    "RiddlerLoc_Underworld_18": [],
    "RiddlerLoc_Underworld_19": [],
    "RiddlerLoc_Underworld_20": ["Remote-Control Batarang", "Explosive Gel"],
    "RiddlerLoc_Underworld_21": [],
    "RiddlerLoc_Underworld_22": ["Disruptor"],
    "RiddlerLoc_Underworld_23": ["Magnetic Blast"],
    "RiddlerLoc_Underworld_24": [],
    "RiddlerLoc_Underworld_25": [],
}

LOCATION_ANY_REQUIREMENTS = {
    "RiddlerLoc_OWB_5": ["Line Launcher", "Freeze Blast"],
    "RiddlerLoc_Steel_2": ["Line Launcher", "Freeze Blast"],
}

UNKNOWN_LOCATIONS = [
    "RiddlerLoc_OWD_9",
    "RiddlerLoc_OWD_10",
    "RiddlerLoc_OWD_23",
    "RiddlerLoc_OWD_24",
]
